if(NOT DEFINED CSV)
    message(FATAL_ERROR "CSV variable is required")
endif()

if(NOT EXISTS "${CSV}")
    message(FATAL_ERROR "Expected CSV file does not exist: ${CSV}")
endif()

file(STRINGS "${CSV}" lines)
list(LENGTH lines line_count)
if(NOT line_count EQUAL 2)
    message(FATAL_ERROR "Expected exactly 2 CSV lines, found ${line_count}")
endif()

list(GET lines 0 header)
set(expected_header "matrix,nrows,ncols,nnz,threads,repeat,median_ms,min_ms,nnz_per_sec,checksum")
if(NOT header STREQUAL expected_header)
    message(FATAL_ERROR "Unexpected CSV header: ${header}")
endif()

list(GET lines 1 row)
if(NOT row MATCHES "^diag5,5,5,5,1,3,")
    message(FATAL_ERROR "Unexpected CSV row: ${row}")
endif()

if(DEFINED EXPECTED_CHECKSUM)
    string(REPLACE "," ";" columns "${row}")
    list(LENGTH columns column_count)
    if(NOT column_count EQUAL 10)
        message(FATAL_ERROR "Expected 10 CSV columns, found ${column_count}: ${row}")
    endif()
    list(GET columns 9 checksum)
    if(NOT checksum MATCHES "^-?[0-9]+(\\.[0-9]+)?([eE][-+]?[0-9]+)?$")
        message(FATAL_ERROR "Checksum is not numeric: ${checksum}")
    endif()
    string(REGEX REPLACE "\\.0+$" "" normalized_checksum "${checksum}")
    string(REGEX REPLACE "\\.0+$" "" normalized_expected "${EXPECTED_CHECKSUM}")
    if(NOT normalized_checksum STREQUAL normalized_expected)
        message(FATAL_ERROR "Unexpected checksum: ${checksum}; expected ${EXPECTED_CHECKSUM}")
    endif()
endif()
